import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ShoppingCartProvider } from '@/context/ShoppingCartContext';

import { getServerSession } from 'next-auth';
import SessionProvider from '@/utils/SessionProvider';
import NavMenu from '@/components/NavMenu';
import Banner from '@/components/Banner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <ShoppingCartProvider>
        <body className={inter.className}>
          <SessionProvider session={session}>
            <Banner />
            <NavMenu />
            {children}
          </SessionProvider>
        </body>
      </ShoppingCartProvider>
    </html>
  );
}
